### ISSUE TITLE
Dialog : aria-live defaulting to polite

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core-react#31]
Original issue: https://github.corp.ebay.com/React/ebayui-core-react/issues/323

https://github.corp.ebay.com/React/ebayui-core-react/blob/2d233a2f76eb318abfd4514ac859452381b7cd42/src/ebay-dialog-base/components/dialogBase.tsx#L87

ebay-ui-core logic 
https://github.com/eBay/ebayui-core/blob/406000378d778c0a62a9edb44aa49cac6869c909/src/components/components/ebay-dialog-base/component.js#L78
 complementary code
https://github.corp.ebay.com/React/ebayui-core-react/blob/2d233a2f76eb318abfd4514ac8594[…]52381b7cd42/src/ebay-dialog-base/components/dialogBase.tsx

**Comment by abiyasa** [comment]
I am closing this since it's not an issue anymore

- @HenriqueLimas has refactor the dialog-base before we went open source. By using makeup.js, it tackled the issue that Arturo mentioned about aria-hider (see [last comment on the original issue](https://github.corp.ebay.com/React/ebayui-core-react/issues/323#issuecomment-2536591))
- From the [original issue's discussion](https://github.corp.ebay.com/React/ebayui-core-react/issues/323#issuecomment-2535139), it seems the our aria-live default value is already 'polite' which is aligned with Marko's implementation:

https://github.com/eBay/ebayui-core/blob/5796c3c48bcb444220ad0387ac85644c40e12515/src/components/components/ebay-dialog-base/index.marko#L75
